# Generated by Django 5.0.4 on 2024-06-05 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contato_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='mostrar_perfil',
            new_name='show',
        ),
    ]
